image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.theia/init_tasks.sh    
vscode:
  extensions:
    - ms-python.python@2019.8.30787
    - esbenp.prettier-vscode@5.7.1
lasson.cornflakes-linter@0.5.1
inter@0.5.1
lasson.cornflakes-linter@0.5.1
ter@0.5.1
lasson.cornflakes-linter@0.5.1
.5.1
ter@0.5.1
lasson.cornflakes-linter@0.5.1

