# Generated by Django 3.1.7 on 2021-03-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210331_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='print_media',
            options={'verbose_name_plural': 'Print Media'},
        ),
        migrations.AlterField(
            model_name='print_media',
            name='category',
            field=models.CharField(choices=[('business_cards', 'Business Cards'), ('leaflets_flyers', 'Leaflets & Flyers'), ('posters', 'Posters')], max_length=20),
        ),
    ]
