# Generated by Django 3.1.7 on 2021-04-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210331_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digital_Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('icon_sets', 'Icon Sets'), ('brand_logos', 'Brand Logos'), ('web_banners', 'Web Banners')], max_length=20)),
                ('size', models.CharField(choices=[('1616', '16 x 16 pixels'), ('3232', '32 x 32 pixels'), ('6464', '64 x 64 pixels'), ('128128', '128 x 128 pixels'), ('256256', '256 x 256 pixels')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Digital Media',
            },
        ),
        migrations.AlterField(
            model_name='print_media',
            name='size',
            field=models.CharField(choices=[('3.5x2.0', '3.5 x 2 inches'), ('2x3.5', '2.0 x 3.5 inches'), ('11x8.5', '11 x 8.5 inches'), ('8.3x5.8', '8.3 x 5.8 inches'), ('5.8x4.1', '5.8 x 4.1 inches'), ('8.3x3.9', '8.3 x 3.9 inches')], max_length=20),
        ),
    ]
