# Generated by Django 3.1.7 on 2021-04-01 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210401_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digital_media',
            old_name='category',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='print_media',
            old_name='category',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='category',
            name='friendly_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='digital_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.digital_media'),
        ),
        migrations.AddField(
            model_name='category',
            name='print_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.print_media'),
        ),
    ]
