# Generated by Django 3.1.7 on 2021-04-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210401_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digital_media',
            old_name='media',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='print_media',
            old_name='media',
            new_name='name',
        ),
    ]
