# Generated by Django 3.1.7 on 2021-04-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
