# Generated by Django 3.1.7 on 2021-04-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='print_media',
            name='name',
            field=models.CharField(choices=[('business_cards', 'Business Cards'), ('leaflets_flyers', 'Leaflets & Flyers'), ('posters', 'Posters')], default='Print Media', max_length=20),
        ),
        migrations.AlterField(
            model_name='print_media',
            name='size',
            field=models.CharField(choices=[('3.5x2', '3.5 x 2 inches'), ('2x3.5', '2 x 3.5 inches'), ('11x8.5', '11 x 8.5 inches'), ('8.3x5.8', '8.3 x 5.8 inches'), ('5.8x4.1', '5.8 x 4.1 inches'), ('8.3x3.9', '8.3 x 3.9 inches')], default='Size', max_length=20),
        ),
    ]
