# Generated by Django 3.1.7 on 2021-04-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210412_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_type', models.CharField(choices=[('print_media', 'Print Media'), ('digital_media', 'Digital Media')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='digital_media',
        ),
        migrations.RemoveField(
            model_name='category',
            name='print_media',
        ),
        migrations.AddField(
            model_name='category',
            name='size_type',
            field=models.CharField(choices=[('print_media', 'Print Media'), ('digital_media', 'Digital Media')], default='print_media', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_print',
            field=models.BooleanField(default=True),
        ),
    ]
