# Generated by Django 3.1.7 on 2021-04-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210414_0621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizeType',
            new_name='MediaType',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='size_type',
            new_name='media_type',
        ),
        migrations.RenameField(
            model_name='mediatype',
            old_name='size_type',
            new_name='media_type',
        ),
    ]
