# Generated by Django 3.1.7 on 2021-04-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210414_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digital_media',
            name='size',
            field=models.CharField(choices=[('1616', '16 x 16 pixels'), ('3232', '32 x 32 pixels'), ('6464', '64 x 64 pixels'), ('128128', '128 x 128 pixels'), ('256256', '256 x 256 pixels')], max_length=20),
        ),
    ]
