# Generated by Django 3.1.7 on 2021-04-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210415_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digital_media',
            name='name',
            field=models.CharField(choices=[('icon_sets', 'Icon Sets'), ('brand_logos', 'Brand Logos'), ('web_banners', 'Web Banners')], max_length=20),
        ),
        migrations.AlterField(
            model_name='print_media',
            name='name',
            field=models.CharField(choices=[('business_cards', 'Business Cards'), ('leaflets_flyers', 'Leaflets & Flyers'), ('posters', 'Posters')], max_length=20),
        ),
        migrations.AlterField(
            model_name='print_media',
            name='size',
            field=models.CharField(choices=[('3.5x2', '3.5 x 2 inches'), ('2x3.5', '2 x 3.5 inches'), ('11x8.5', '11 x 8.5 inches'), ('8.3x5.8', '8.3 x 5.8 inches'), ('5.8x4.1', '5.8 x 4.1 inches'), ('8.3x3.9', '8.3 x 3.9 inches')], max_length=20),
        ),
    ]
