# Generated by Django 3.1.7 on 2021-04-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210415_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digital_media',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='print_media',
            old_name='name',
            new_name='category',
        ),
    ]
