# Generated by Django 3.1.7 on 2021-04-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20210415_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digital_media',
            name='category',
        ),
        migrations.RemoveField(
            model_name='print_media',
            name='category',
        ),
        migrations.AlterField(
            model_name='digital_media',
            name='name',
            field=models.CharField(choices=[('icon_sets', 'Icon Sets'), ('brand_logos', 'Brand Logos'), ('web_banners', 'Web Banners')], max_length=20),
        ),
        migrations.AlterField(
            model_name='print_media',
            name='name',
            field=models.CharField(choices=[('business_cards', 'Business Cards'), ('leaflets_flyers', 'Leaflets & Flyers'), ('posters', 'Posters')], max_length=20),
        ),
    ]
