# Generated by Django 3.1.7 on 2021-04-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20210415_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digital_media',
            old_name='size',
            new_name='sizes',
        ),
        migrations.RenameField(
            model_name='print_media',
            old_name='size',
            new_name='sizes',
        ),
    ]
