# Generated by Django 3.1.7 on 2021-04-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210416_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_print',
            new_name='is_print_media',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_digital',
        ),
    ]
