# Generated by Django 3.1.7 on 2021-04-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20210422_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_print_media',
            field=models.BooleanField(default=False),
        ),
    ]
